spring:
  datasource:
   druid:
      url: jdbc:mysql://1.1.1.1:3306/prilic?serverTimezone=GMT%2B8
      username: root
      password: root
      connectionProperties: druid.stat.slowSqlMillis=5000;druid.stat.logSlowSql=true;
