spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/ku?serverTimezone=GMT%2B8
      username: ku
      password: mCCR7TDtP22xEEKM
      connectionProperties: druid.stat.slowSqlMillis=5000;druid.stat.logSlowSql=true;





